### ISSUE TITLE
Linebreaks not preserved on display

### ISSUE THREAD

**Issue by spellsmith** [derula/swlrp-server#23] opened 2017-07-28 01:55 UTC
If you edit a profile and include blank lines / carriage returns in the profile to make paragraphs, when you save/preview it, the line breaks are ignored / removed.

**Comment by derula** [comment] 2017-07-29 14:02
This is technically a duplicate of #18 / invalid. It will be fixed with #18, and we need to fix #18 before release anyway. Hence, I'm closing this issue..

**Closed as completed by derula** 2017-07-29 14:02 UTC
